spring.application.name=BackEnd

spring.mongodb.uri= ${MONGO_URI:mongodb+srv://nghia:cJdChOPxuj4Y5C3F@cluster0.oty6c1e.mongodb.net/taskFlow_db?retryWrites=true&w=majority&appName=Cluster0}

jwt.secret=8f3a9c2d7b6e4a1f9c0d5e7a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8g9h0
jwt.expiration= 900000
#86400000
jwt.refresh=604800000

#server
server.port=${SERVER_PORT:8080}
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=6000
#docker start c57d0e3c1d8c
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nghia120425@gmail.com
spring.mail.password=inql heyq jdjp cnis

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- OAUTH2 GOOGLE CONFIG ---
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile

# --- OAUTH2 GITHUB CONFIG ---
spring.security.oauth2.client.registration.github.client-id=YOUR_GITHUB_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_GITHUB_CLIENT_SECRET
spring.security.oauth2.client.registration.github.scope=user:email,read:user

# -- SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

